spring.datasource.url=jdbc:mysql://192.168.48.1:3307/bindingtest?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.locations=classpath:db/migration/mysql
spring.flyway.validate-on-migrate=false
spring.jooq.sql-dialect=MYSQL
busybee.file-storage.directory=${java.io.tmpdir}/busybee-uploads
busybee.ocr.command=../tesseract_mock_java/build/install/tesseract_mock_java/bin/tesseract_mock_java
